---
all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
  vars:
    es_host: "http://localhost:9200"
    es_user: "elastic"
    es_password: "changeme"
