replicaCount: 2

image:
  repository: ghcr.io/anupanupranjan-gif/search-api
  tag: 9685805
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

elasticsearch:
  host: "searchx-es-http.elasticsearch.svc.cluster.local"
  port: "9200"
  username: "elastic"
  passwordSecret:
    name: elasticsearch-credentials
    key: password

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "1000m"

probes:
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 10
  liveness:
    initialDelaySeconds: 60
    periodSeconds: 30

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
