apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: searchx
  namespace: elasticsearch
spec:
  version: 8.12.2
  count: 1
  elasticsearchRef:
    name: searchx
  config:
    server.basePath: /kibana
    server.rewriteBasePath: true
    server.ssl.enabled: false
  podTemplate:
    spec:
      containers:
        - name: kibana
          readinessProbe:
            httpGet:
              path: /kibana/login
              port: 5601
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1Gi
              cpu: 1000m
