apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: product-events
  namespace: kafka
  labels:
    strimzi.io/cluster: searchx-kafka
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000
    cleanup.policy: delete
