apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.konghq.com
    chart: kong
    targetRevision: "2.38.0"
    helm:
      values: |
        image:
          repository: kong
          tag: "3.6"
        env:
          database: "off"
          declarative_config: /kong_dbless/kong.yaml
        ingressController:
          enabled: false
        proxy:
          enabled: true
          type: ClusterIP
        admin:
          enabled: true
          type: ClusterIP
          http:
            enabled: true
            containerPort: 8001
            servicePort: 8001
        dblessConfig:
          configMap: kong-declarative-config
  destination:
    server: https://kubernetes.default.svc
    namespace: kong
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
