#!/bin/bash
# Install Redis for NexaRank/SearchX (rules-cache-version invalidation,
# search-result cache). Run this once on a fresh Kind cluster.
#
# This had no committed install script anywhere prior to NR-155 - it was
# deployed imperatively and never captured in git (same class of gap as the
# nexarank-credentials/elasticsearch-credentials Secrets documented in
# CLAUDE.md's Post-Rebuild Verification Findings). Reconstructed here from
# `helm get values redis -n default` against the live cluster so a rebuild
# doesn't silently lose the TLS decision made in this session.
#
# auth.enabled=false: matches nexarank-api/search-api, which never send a
# Redis password (see CLAUDE.md's "Undocumented hard dependency — Redis").
# Not fixed here - a real password would need wiring on both app sides too.
#
# tls.authClients=false: TLS encrypts the channel without requiring client
# certificates - nexarank-api/search-api trust the auto-generated CA's
# server cert but don't present client certs (see RedisSslConfig in both
# app repos). Full mTLS would need distributing client certs to both apps.

helm install redis bitnami/redis \
  --namespace default \
  --set architecture=standalone \
  --set auth.enabled=false \
  --set tls.enabled=true \
  --set tls.autoGenerated=true \
  --set tls.authClients=false
